# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ SBOL3 ]
  pull_request:
    branches: [ SBOL3 ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: sbol3.tex
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: sbol3.pdf


